// "use client"
import type { Metadata } from "next";
import { Roboto as RobotoFont } from "next/font/google";
import "./globals.css";
import Navbar from "./components/landing/Navbar";
import { Toaster } from "./components/ui/sonner";
import {Providers} from "./Providers";
import {ThemeToggle} from "./components/ui/ThemeToggle";

const roboto = RobotoFont({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
          <Providers>
            <Navbar />
            {children}
            <ThemeToggle/>
            <Toaster />
          </Providers>
      </body>
    </html>
  );
}
