// "use client"
import type { Metadata } from "next";
import { Cabin, Sora } from "next/font/google";
import "./globals.css";
import Navbar from "./components/landing/Navbar";
import { Toaster } from "./components/ui/sonner";
import { Providers } from "./Providers";
import { ThemeToggle } from "./components/ui/ThemeToggle";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  display: "swap",
});

const cabin = Cabin({
  variable: "--font-cabin",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${cabin.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`${cabin.className} min-h-full flex flex-col`}>
        <Providers>
          <Navbar />
          {children}
          <ThemeToggle />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
